-- core plugins
require("custom.options")
require("custom.keymaps")
require("custom.packer")
require("custom.lsp_config")
require("custom.completions")
require("custom.treesitter")
require("custom.bufferline")
require("custom.trouble")
require("custom.noice")

-- non critical plugins
-- require("custom.tokyonight")
require("custom.dap")
require("custom.catppuccin")
require("custom.lualine")
require("custom.neotree")
require("custom.gitsigns")
require("custom.diagnostics")
require("custom.autocommands")
require("custom.alpha")
require("custom.toggleterm")
require("custom.whitespace")
require("custom.osc52")
require("custom.colorizer")
require("custom.neorg")
-- require("custom.notebook")
--require("custom.wilder")
